added admin decision and contact person functionality"
techx/projx-web pull request #2
Opened 2018-08-01 08:26 UTC by AnuragGolla

The initial commit was made before the merge of a different PR, so it was reverted then that PR was merged and then the reverted commit was reverted again and pushed to this new branch and is now in this new PR.

2018-08-02 05:49 UTC, Anton-Cao requested changes
Good work! Left some minor comments.

2018-08-02 05:49 UTC, Anton-Cao commented on client/assets/js/admin-controller.js
> +    // store projex members
projex -> projx

2018-08-02 05:49 UTC, Anton-Cao commented on client/assets/js/admin-controller.js
> +                    };
remove empty if block

2018-08-02 05:49 UTC, Anton-Cao commented on client/assets/js/admin-controller.js
> +            // project.private.contact = project.private.contact.toLowerCase();
remove comments

2018-08-02 05:49 UTC, Anton-Cao commented on client/views/home.html
>                    <div class="ui tag yellow label" ng-show="project.display.complete==='yes'">Application complete</div>
could consider changing "Application complete" to "Application awaiting review"

2018-08-02 05:49 UTC, Anton-Cao commented on client/views/project.html
>          <div class="ui tag yellow label" ng-show="projectDisplay.complete==='yes'">Application complete</div>
same as above

2018-08-02 05:49 UTC, Anton-Cao commented on client/assets/js/admin-controller.js
> +angular.module('portal').controller('adminController', function ($scope, $http, $location, $routeParams) {
why do we need `routeParams` here?

2018-08-02 05:49 UTC, Anton-Cao commented on server/routes/user.js
> +        "team": config.projxTeam
add `projxTeam` to example `config.json` in readme

2018-08-02 05:49 UTC, Anton-Cao commented on server/routes/user.js
>  router.get('/countdown', function(req,res,next) {
spaces between the method parameters

2018-08-02 05:49 UTC, Anton-Cao commented on server/routes/user.js
> +router.get('/projxTeam', function(req,res,next) {
spaces between the method parameters

2018-08-03 06:21 UTC, Anton-Cao requested changes
Just left one small comment.

2018-08-03 06:21 UTC, Anton-Cao commented on client/assets/js/admin-controller.js
> +                    // };
will this be used in the future? if not, the comments can be removed

2018-08-03 07:59 UTC, AnuragGolla commented
admin decision privileges and assignment of contact person

2018-08-03 08:00 UTC, merged